packages:
  - packages/*
  - integrations/*
  - sdks/*
  - services/*
  - apps/*

autoInstallPeers: false

allowBuilds:
  esbuild: true
  isolated-vm: true
  msw: true

overrides:
  '@jridgewell/sourcemap-codec': 1.5.5
  fastq: 1.20.1
