packages:
  - packages/*
  - integrations/*
  - sdks/*
  - services/*

autoInstallPeers: false

allowBuilds:
  esbuild: true
  isolated-vm: true

onlyBuiltDependencies:
  - esbuild
  - isolated-vm
  - '@prisma/client'
  - '@prisma/engines'
  - prisma

overrides:
  '@jridgewell/sourcemap-codec': 1.5.5
  fastq: 1.20.1
