from __future__ import annotations

from typing import Any, Protocol

from pydantic import BaseModel, ConfigDict, Field

from .context import AdapterRequestContext


class ProviderResult(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)
    provider: str
    provider_operation_id: str | None = None
    status: str
    evidence: dict[str, Any] = Field(default_factory=dict)


class BankingAdapter(Protocol):
    async def create_link(self, context: AdapterRequestContext, request: dict[str, Any]) -> ProviderResult: ...
    async def read_accounts(self, context: AdapterRequestContext, reference: str) -> ProviderResult: ...
    async def read_transactions(self, context: AdapterRequestContext, reference: str) -> ProviderResult: ...


class EvidenceAdapter(Protocol):
    async def request(self, context: AdapterRequestContext, evidence: dict[str, Any]) -> ProviderResult: ...
    async def status(self, context: AdapterRequestContext, reference: str) -> ProviderResult: ...


class LenderAdapter(Protocol):
    async def submit(self, context: AdapterRequestContext, package: dict[str, Any]) -> ProviderResult: ...
    async def status(self, context: AdapterRequestContext, reference: str) -> ProviderResult: ...
    async def reconcile(self, context: AdapterRequestContext) -> ProviderResult: ...


class ESignAdapter(Protocol):
    async def create_envelope(self, context: AdapterRequestContext, request: dict[str, Any]) -> ProviderResult: ...
    async def read_envelope(self, context: AdapterRequestContext, reference: str) -> ProviderResult: ...
    async def void_envelope(self, context: AdapterRequestContext, reference: str, reason: str) -> ProviderResult: ...


class PaymentAdapter(Protocol):
    async def create(self, context: AdapterRequestContext, request: dict[str, Any]) -> ProviderResult: ...
    async def status(self, context: AdapterRequestContext, reference: str) -> ProviderResult: ...
    async def reconcile(self, context: AdapterRequestContext) -> ProviderResult: ...


class ObjectStorageAdapter(Protocol):
    async def upload_intent(self, context: AdapterRequestContext, metadata: dict[str, Any]) -> ProviderResult: ...
    async def metadata(self, context: AdapterRequestContext, object_id: str) -> ProviderResult: ...


class MalwareScanner(Protocol):
    async def scan(self, context: AdapterRequestContext, content: bytes) -> ProviderResult: ...
