camel.main.name=CodestraProtocolGateway
camel.main.basePackageScan=co.codestra.gateway
camel.main.autoConfigurationFailFast=true
camel.main.devConsoleEnabled=false
camel.main.dumpRoutes=false
camel.main.logMask=true
camel.main.profile=prod
camel.server.enabled=true
camel.server.port=8080
camel.server.staticEnabled=false
camel.management.enabled=false
