export type UiControlType = "text" | "email" | "tel" | "textarea" | "select" | "date" | "number" | "checkbox" | "radio" | "rating" | "nps" | "yes_no" | "matrix";

export interface UiOption { value: string; label: string }
export interface UiControl { id: string; name: string; label: string; type: UiControlType; required: boolean; options?: readonly UiOption[]; helpText?: string; min?: number; max?: number; maxLength?: number; autocomplete?: string; inputMode?: "text" | "email" | "tel" | "numeric" | "decimal" | "search" | "url"; ariaDescription?: string }
export interface UiSection { id: string; title?: string; description?: string; controls: readonly UiControl[] }
export interface IntakeUiModel { id: string; title: string; description?: string; sections: readonly UiSection[]; submitLabel: string; progress?: { current: number; total: number }; privacyNotice?: string; mode: "form" | "survey" | "callback" }
export interface SubmitState<T> { status: "idle" | "submitting" | "success" | "error"; value?: T; error?: string }

export class IntakeUiController<TPayload, TReceipt = unknown> {
  private _state: SubmitState<TReceipt> = { status: "idle" };
  private readonly listeners = new Set<(state: SubmitState<TReceipt>) => void>();
  constructor(readonly model: IntakeUiModel, private readonly buildPayload: (values: Record<string, unknown>) => TPayload, private readonly submitter: (payload: TPayload) => Promise<TReceipt>) {}
  get state(): SubmitState<TReceipt> { return this._state; }
  subscribe(listener: (state: SubmitState<TReceipt>) => void): () => void { this.listeners.add(listener); listener(this._state); return () => this.listeners.delete(listener); }
  async submit(values: Record<string, unknown>): Promise<TReceipt> { this.setState({ status: "submitting" }); try { const payload = this.buildPayload(values); const receipt = await this.submitter(payload); this.setState({ status: "success", value: receipt }); return receipt; } catch (error) { const message = error instanceof Error ? error.message : "Submission failed"; this.setState({ status: "error", error: message }); throw error; } }
  reset(): void { this.setState({ status: "idle" }); }
  private setState(state: SubmitState<TReceipt>): void { this._state = state; for (const listener of this.listeners) listener(state); }
}
export interface PopupConfig { id: string; trigger: "manual" | "delay" | "exit_intent" | "scroll"; delayMs?: number; scrollPercent?: number; dismissForMs?: number }
export class IntakePopupController { private open = false; private dismissedAt?: number; constructor(readonly config: PopupConfig, private readonly now: () => number = Date.now) {} shouldOpen(signal: { kind: "delay" | "exit_intent" | "scroll"; value?: number }): boolean { if (this.open || this.isDismissed()) return false; if (this.config.trigger === "delay" && signal.kind === "delay") return (signal.value ?? 0) >= (this.config.delayMs ?? 0); if (this.config.trigger === "exit_intent" && signal.kind === "exit_intent") return true; if (this.config.trigger === "scroll" && signal.kind === "scroll") return (signal.value ?? 0) >= (this.config.scrollPercent ?? 50); return false; } show(): void { if (!this.isDismissed()) this.open = true; } hide(): void { this.open = false; } dismiss(): void { this.open = false; this.dismissedAt = this.now(); } isOpen(): boolean { return this.open; } isDismissed(): boolean { if (!this.dismissedAt) return false; return this.now() - this.dismissedAt < (this.config.dismissForMs ?? 0); } }
export interface CallbackRequestValues { name?: string; phone: string; preferredTime?: string; language?: string; reason?: string; consent: boolean }
export function buildCallbackUiModel(title = "Request a callback"): IntakeUiModel { return { id: "codestra-callback", title, mode: "callback", submitLabel: "Request callback", sections: [{ id: "callback", controls: [{ id: "name", name: "name", label: "Name", type: "text", required: false, autocomplete: "name" }, { id: "phone", name: "phone", label: "Phone", type: "tel", required: true, autocomplete: "tel", inputMode: "tel" }, { id: "preferredTime", name: "preferredTime", label: "Preferred callback time", type: "text", required: false }, { id: "language", name: "language", label: "Language", type: "text", required: false }, { id: "reason", name: "reason", label: "Reason", type: "textarea", required: false, maxLength: 2000 }, { id: "consent", name: "consent", label: "I agree to be contacted about this request.", type: "checkbox", required: true }] }] }; }
export interface MountOptions { onSubmit: (values: Record<string, unknown>) => Promise<unknown>; document?: Document }
export function mountIntakeUi(root: HTMLElement, model: IntakeUiModel, options: MountOptions): () => void { const doc = options.document ?? root.ownerDocument; const form = doc.createElement("form"); form.noValidate = true; form.setAttribute("aria-labelledby", `${model.id}-title`); const title = doc.createElement("h2"); title.id = `${model.id}-title`; title.textContent = model.title; form.append(title); for (const section of model.sections) { const fieldset = doc.createElement("fieldset"); if (section.title) { const legend = doc.createElement("legend"); legend.textContent = section.title; fieldset.append(legend); } for (const control of section.controls) fieldset.append(renderControl(doc, control)); form.append(fieldset); } const status = doc.createElement("div"); status.setAttribute("role", "status"); status.setAttribute("aria-live", "polite"); const button = doc.createElement("button"); button.type = "submit"; button.textContent = model.submitLabel; form.append(button, status); const submit = async (event: Event) => { event.preventDefault(); button.disabled = true; status.textContent = "Submitting…"; try { await options.onSubmit(formValues(form)); status.textContent = "Submitted successfully."; } catch (error) { status.textContent = error instanceof Error ? error.message : "Submission failed."; } finally { button.disabled = false; } }; form.addEventListener("submit", submit); root.replaceChildren(form); return () => { form.removeEventListener("submit", submit); root.replaceChildren(); }; }
function renderControl(doc: Document, control: UiControl): HTMLElement { const wrapper = doc.createElement("div"); const label = doc.createElement("label"); label.htmlFor = control.id; label.textContent = control.label; wrapper.append(label); let element: HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement; if (control.type === "textarea") element = doc.createElement("textarea"); else if (control.type === "select") { const select = doc.createElement("select"); for (const option of control.options ?? []) { const node = doc.createElement("option"); node.value = option.value; node.textContent = option.label; select.append(node); } element = select; } else { const input = doc.createElement("input"); input.type = control.type === "yes_no" ? "checkbox" : control.type === "nps" || control.type === "rating" ? "number" : control.type === "radio" ? "radio" : control.type; if (control.min !== undefined) input.min = String(control.min); if (control.max !== undefined) input.max = String(control.max); if (control.autocomplete) input.setAttribute("autocomplete", control.autocomplete); if (control.inputMode) input.inputMode = control.inputMode; element = input; } element.id = control.id; element.setAttribute("name", control.name); if (control.required) element.required = true; if (control.maxLength !== undefined && "maxLength" in element) element.maxLength = control.maxLength; if (control.ariaDescription) element.setAttribute("aria-description", control.ariaDescription); wrapper.append(element); if (control.helpText) { const help = doc.createElement("small"); help.textContent = control.helpText; wrapper.append(help); } return wrapper; }
function formValues(form: HTMLFormElement): Record<string, unknown> { const result: Record<string, unknown> = {}; const data = new FormData(form); for (const [key, value] of data.entries()) { const current = result[key]; const normalized = typeof value === "string" ? value : value.name; if (current === undefined) result[key] = normalized; else result[key] = Array.isArray(current) ? [...current, normalized] : [current, normalized]; } for (const checkbox of form.querySelectorAll<HTMLInputElement>('input[type="checkbox"][name]')) { if (!(checkbox.name in result)) result[checkbox.name] = false; else result[checkbox.name] = checkbox.checked; } return result; }
